// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYPZn3t8_W06bOWl5ELWWBOc1EponTBMM',
    appId: '1:226621537996:web:fb224e9c3339ba3f370c69',
    messagingSenderId: '226621537996',
    projectId: 'loginapp-403c3',
    authDomain: 'loginapp-403c3.firebaseapp.com',
    storageBucket: 'loginapp-403c3.appspot.com',
    measurementId: 'G-QVC9J1MJJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZJFgN-nF2slwCyxHSxfAMIUjehl7jT-Q',
    appId: '1:226621537996:android:321bf91a46b666ca370c69',
    messagingSenderId: '226621537996',
    projectId: 'loginapp-403c3',
    storageBucket: 'loginapp-403c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTx3uCPPHCSXwJXcL6hVLK5REFxwcArB4',
    appId: '1:226621537996:ios:ad6badf34d226689370c69',
    messagingSenderId: '226621537996',
    projectId: 'loginapp-403c3',
    storageBucket: 'loginapp-403c3.appspot.com',
    iosClientId:
        '226621537996-tj8bmtlucr4fdhtv58tvk20bv3smhi0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTx3uCPPHCSXwJXcL6hVLK5REFxwcArB4',
    appId: '1:226621537996:ios:ad6badf34d226689370c69',
    messagingSenderId: '226621537996',
    projectId: 'loginapp-403c3',
    storageBucket: 'loginapp-403c3.appspot.com',
    iosClientId:
        '226621537996-tj8bmtlucr4fdhtv58tvk20bv3smhi0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );
}
